name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs: 
  run-lint:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: install deps
      run: yarn

    - name: check lint
      run: yarn lint

  run-test-and-codecov:
    - name: checkout
      uses: actions/checkout@v3

    - name: install deps
      run: yarn

    - name: run test
      run: yarn test

    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v3.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
